%YAML:1.0

DataType: 0
#0 : EUROC
#1 : ANDROID
#2 : IOS

TrackerType: 2
#0 : OPTICAL FLOW
#1 : SEMI DENSE
#2 : DENSE_SPARSE

PyramidLevel: 3
# for DENSE_SPARSE levlel =3

xGridNum: 5 # 2^5
yGridNum: 5 # 2^5

xPixelSearchNum: 50
yPixelSearchNum: 50

########## Debug Obtion ##########
Debug: 1
show_threshold: 0
show_feature: 0


